version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - /data/app/mongodb:/data/db
    networks:
      - backend

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
      #    ports:
      #      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
    networks:
      - backend

  node-app:
    #image: my-rego-app:test
    build:
      context: ./my-rego-app
      dockerfile: Dockerfile.node
    container_name: node-app
    restart: always
    environment:
      - MONGO_URL=mongodb://mongo:27017
    depends_on:
      - mongo
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "8081:8081"
      - "8443:8443"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - node-app
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge

